version: '3'

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - sftp:/home/admindocker/upload
    environment:
      - SFTP_USERS=admindocker:poiu/123:1001

volumes:
  sftp:
